2022-08-01 18:10:15.851 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.851 UTC [122921] STATEMENT:  CREATE SCHEMA public; SET search_path TO public;
2022-08-01 18:10:15.852 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 14
2022-08-01 18:10:15.852 UTC [122921] STATEMENT:  CREATE TABLE tab_2 (a int, t box);
2022-08-01 18:10:15.852 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 13
2022-08-01 18:10:15.852 UTC [122921] STATEMENT:  INSERT INTO tab_2
	  SELECT (x - 1) * 100 + y, box(point(x * 10, y * 10), point(x * 10 + 5, y * 10 + 5))
	  FROM generate_series(1, 100) x,
	       generate_series(1, 100) y;
2022-08-01 18:10:15.852 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.852 UTC [122921] STATEMENT:  CREATE INDEX tab1 ON tab_2 USING spgist(t);
2022-08-01 18:10:15.852 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.852 UTC [122921] STATEMENT:  SET enable_seqscan = ON;
2022-08-01 18:10:15.852 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.852 UTC [122921] STATEMENT:  SET enable_indexscan = OFF;
2022-08-01 18:10:15.852 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 120
2022-08-01 18:10:15.852 UTC [122921] STATEMENT:  CREATE TABLE c AS
	SELECT rank() OVER (ORDER BY t <-> point '123,456') tab1_pkey, t <-> point '123,456' gin_tbl, b
	FROM tab_2;
2022-08-01 18:10:15.852 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.852 UTC [122921] STATEMENT:  SET enable_bitmapscan = ON;
2022-08-01 18:10:15.852 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 22
2022-08-01 18:10:15.852 UTC [122921] STATEMENT:  SELECT count(*) FROM tab_2 WHERE t <<  box '((100,200),(300,500))';
2022-08-01 18:10:15.852 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 22
2022-08-01 18:10:15.852 UTC [122921] STATEMENT:  SELECT count(*) FROM tab_2 WHERE t >>  box '((100,200),(300,500))';
2022-08-01 18:10:15.852 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 22
2022-08-01 18:10:15.852 UTC [122921] STATEMENT:  SELECT count(*) FROM tab_2 WHERE t >>  box '((100,200),(300,500))';
2022-08-01 18:10:15.853 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 22
2022-08-01 18:10:15.853 UTC [122921] STATEMENT:  SELECT count(*) FROM tab_2 WHERE t |&> box '((100,200),(300,500))';
2022-08-01 18:10:15.853 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.853 UTC [122921] STATEMENT:  SET enable_indexscan = ON;
2022-08-01 18:10:15.853 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.853 UTC [122921] STATEMENT:  RESET enable_seqscan;
2022-08-01 18:10:15.853 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.853 UTC [122921] STATEMENT:  RESET enable_indexscan;
2022-08-01 18:10:15.853 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.853 UTC [122921] STATEMENT:  RESET SESSION AUTHORIZATION;
2022-08-01 18:10:15.853 UTC [122921] WARNING:  there is no transaction in progress
2022-08-01 18:10:15.853 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.853 UTC [122921] STATEMENT:  DISCARD ALL;
2022-08-01 18:10:15.853 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 24
2022-08-01 18:10:15.853 UTC [122921] STATEMENT:  SELECT n.nspname 
	FROM pg_catalog.pg_namespace n 
	WHERE n.nspname !~ '^pg_' AND n.nspname <> 'information_schema';
2022-08-01 18:10:15.853 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.853 UTC [122921] STATEMENT:  CREATE SCHEMA public; SET search_path TO public;
2022-08-01 18:10:15.854 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.854 UTC [122921] STATEMENT:  GRANT USAGE ON LANGUAGE c TO PUBLIC;
2022-08-01 18:10:15.854 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.854 UTC [122921] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user1;
2022-08-01 18:10:15.854 UTC [122921] ERROR:  role "regress_priv_user2" does not exist
2022-08-01 18:10:15.854 UTC [122921] STATEMENT:  GRANT USAGE ON LANGUAGE sql TO regress_priv_user2;
2022-08-01 18:10:15.854 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.854 UTC [122921] STATEMENT:  CREATE PROCEDURE tab_2(int) AS 'select $1;' LANGUAGE sql;
2022-08-01 18:10:15.854 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.854 UTC [122921] STATEMENT:  GRANT EXECUTE ON FUNCTION tab_2(int), tab_2(int), tab_2(int) TO regress_priv_user2;
2022-08-01 18:10:15.854 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.854 UTC [122921] STATEMENT:  REVOKE ALL ON PROCEDURE tab_2(int) FROM PUBLIC;
2022-08-01 18:10:15.854 UTC [130717] PANIC:  could not open critical system index 2662
2022-08-01 18:10:15.855 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.855 UTC [122921] STATEMENT:  GRANT USAGE ON FUNCTION tab_2(int) TO regress_priv_user3;
2022-08-01 18:10:15.855 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.855 UTC [122921] STATEMENT:  GRANT USAGE ON FUNCTION tab_2(int) TO regress_priv_user3;
2022-08-01 18:10:15.855 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.855 UTC [122921] STATEMENT:  GRANT ALL PRIVILEGES ON FUNCTION priv_testfunc_nosuch(int) TO regress_priv_user4;
2022-08-01 18:10:15.855 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.855 UTC [122921] STATEMENT:  CREATE FUNCTION priv_testfunc4(boolean) RETURNS text
	  AS 'select col1 from atest2 where col2 = $1;'
	  LANGUAGE sql SECURITY DEFINER;
2022-08-01 18:10:15.855 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.855 UTC [122921] STATEMENT:  GRANT EXECUTE ON FUNCTION priv_testfunc4(boolean) TO regress_priv_user3;
2022-08-01 18:10:15.855 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 8
2022-08-01 18:10:15.855 UTC [122921] STATEMENT:  SELECT tab_2(5), tab_2(5);
2022-08-01 18:10:15.855 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 8
2022-08-01 18:10:15.855 UTC [122921] STATEMENT:  SELECT tab_2(x) FROM (VALUES (1), (2), (3)) _(x);
2022-08-01 18:10:15.855 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 6
2022-08-01 18:10:15.855 UTC [122921] STATEMENT:  CALL tab_2(6);
2022-08-01 18:10:15.855 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.855 UTC [122921] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user3;
2022-08-01 18:10:15.855 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 8
2022-08-01 18:10:15.855 UTC [122921] STATEMENT:  SELECT tab_2(5);
2022-08-01 18:10:15.856 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 8
2022-08-01 18:10:15.856 UTC [122921] STATEMENT:  SELECT tab_2(x) FROM (VALUES (1), (2), (3)) _(x);
2022-08-01 18:10:15.856 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.856 UTC [122921] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user4;
2022-08-01 18:10:15.856 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 8
2022-08-01 18:10:15.856 UTC [122921] STATEMENT:  SELECT tab_2(5);
2022-08-01 18:10:15.856 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.856 UTC [122921] STATEMENT:  DROP FUNCTION tab_2(int);
2022-08-01 18:10:15.856 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.856 UTC [122921] STATEMENT:  RESET SESSION AUTHORIZATION;
2022-08-01 18:10:15.856 UTC [122921] WARNING:  there is no transaction in progress
2022-08-01 18:10:15.856 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.856 UTC [122921] STATEMENT:  DISCARD ALL;
2022-08-01 18:10:15.856 UTC [122921] ERROR:  could not find pg_class tuple for index 2662 at character 24
2022-08-01 18:10:15.856 UTC [122921] STATEMENT:  SELECT n.nspname 
	FROM pg_catalog.pg_namespace n 
	WHERE n.nspname !~ '^pg_' AND n.nspname <> 'information_schema';
2022-08-01 18:10:15.856 UTC [122921] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 18:10:15.856 UTC [122921] STATEMENT:  CREATE SCHEMA public; SET search_path TO public;
2022-08-01 18:10:15.857 UTC [117292] LOG:  server process (PID 130717) was terminated by signal 6: Aborted
2022-08-01 18:10:15.857 UTC [117292] LOG:  terminating any other active server processes
2022-08-01 18:10:15.908 UTC [117292] LOG:  all server processes terminated; reinitializing
2022-08-01 18:10:15.927 UTC [130730] LOG:  database system was interrupted; last known up at 2022-08-01 18:09:52 UTC
2022-08-01 18:10:15.927 UTC [130731] FATAL:  the database system is in recovery mode
2022-08-01 18:10:15.929 UTC [130734] FATAL:  the database system is in recovery mode
2022-08-01 18:10:15.931 UTC [130735] FATAL:  the database system is in recovery mode
2022-08-01 18:10:15.937 UTC [117292] LOG:  received smart shutdown request
2022-08-01 18:10:15.960 UTC [130730] LOG:  recovered replication state of node 5 to 0/AABBCCDD
2022-08-01 18:10:15.960 UTC [130730] LOG:  recovered replication state of node 6 to 0/0
2022-08-01 18:10:15.960 UTC [130730] LOG:  database system was not properly shut down; automatic recovery in progress
