2022-08-01 20:16:23.803 UTC [118163] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 20:16:23.803 UTC [118163] STATEMENT:  CREATE SCHEMA pub_test1;
2022-08-01 20:16:23.804 UTC [118163] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 20:16:23.804 UTC [118163] STATEMENT:  CREATE SCHEMA pub_test2;
2022-08-01 20:16:23.804 UTC [118163] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 20:16:23.804 UTC [118163] STATEMENT:  SET client_min_messages = 'ERROR';
2022-08-01 20:16:23.804 UTC [118163] ERROR:  could not find pg_class tuple for index 2662 at character 149
2022-08-01 20:16:23.804 UTC [118163] STATEMENT:  SELECT oid, pubname,
	  pg_catalog.pg_get_userbyid(pubowner) AS owner,
	  puballtables, pubinsert, pubupdate, pubdelete, pubtruncate, pubviaroot
	FROM pg_catalog.pg_publication
	WHERE pubname OPERATOR(pg_catalog.~) '^(testpub1_forschema)$' COLLATE pg_catalog.default
	ORDER BY 2;
2022-08-01 20:16:23.804 UTC [118163] ERROR:  could not find pg_class tuple for index 2662 at character 34
2022-08-01 20:16:23.804 UTC [118163] STATEMENT:  SELECT n.nspname, c.relname
	FROM pg_catalog.pg_class c,
	     pg_catalog.pg_namespace n,
	     pg_catalog.pg_publication_rel pr
	WHERE c.relnamespace = n.oid
	  AND c.oid = pr.prrelid
	  AND pr.prpubid = '28564'
	ORDER BY 1,2
	;
2022-08-01 20:16:23.804 UTC [118163] ERROR:  could not find pg_class tuple for index 2662 at character 34
2022-08-01 20:16:23.804 UTC [118163] STATEMENT:  SELECT n.nspname, c.relname
	FROM pg_catalog.pg_class c,
	     pg_catalog.pg_namespace n,
	     pg_catalog.pg_publication_rel pr
	WHERE c.relnamespace = n.oid
	  AND c.oid = pr.prrelid
	  AND pr.prpubid = '28566'
	ORDER BY 1,2
	;
2022-08-01 20:16:23.804 UTC [118163] ERROR:  could not find pg_class tuple for index 2662 at character 149
2022-08-01 20:16:23.804 UTC [118163] STATEMENT:  SELECT oid, pubname,
	  pg_catalog.pg_get_userbyid(pubowner) AS owner,
	  puballtables, pubinsert, pubupdate, pubdelete, pubtruncate, pubviaroot
	FROM pg_catalog.pg_publication
	WHERE pubname OPERATOR(pg_catalog.~) '^(testpub1_forschema)$' COLLATE pg_catalog.default
	ORDER BY 2;
2022-08-01 20:16:23.804 UTC [118163] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 20:16:23.804 UTC [118163] STATEMENT:  CREATE SCHEMA pub_testpart1;
2022-08-01 20:16:23.805 UTC [118163] ERROR:  could not find pg_class tuple for index 2662 at character 14
2022-08-01 20:16:23.805 UTC [118163] STATEMENT:  CREATE TABLE pub_testpart2.fc partition of pub_testpart1.mr_inoutparam_succeed for values in (1);
2022-08-01 20:16:23.805 UTC [118163] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 20:16:23.805 UTC [118163] STATEMENT:  DROP PUBLICATION testpub_fortable_forschema;
2022-08-01 20:16:23.805 UTC [118163] ERROR:  schema "pub_test1" does not exist
2022-08-01 20:16:23.805 UTC [118163] STATEMENT:  DROP SCHEMA pub_test1 CASCADE;
2022-08-01 20:16:23.805 UTC [118163] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 20:16:23.805 UTC [118163] STATEMENT:  SET client_min_messages = 'ERROR';
2022-08-01 20:16:23.805 UTC [118163] ERROR:  schema "sch2" does not exist at character 14
2022-08-01 20:16:23.805 UTC [118163] STATEMENT:  CREATE TABLE sch2.voo PARTITION OF sch1.test_multirange_gist FOR VALUES FROM (1) to (10);
2022-08-01 20:16:23.805 UTC [118163] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 20:16:23.805 UTC [118163] STATEMENT:  CREATE PUBLICATION pub FOR TABLE sch2.test_multirange_gist WITH (PUBLISH_VIA_PARTITION_ROOT=1);
2022-08-01 20:16:23.805 UTC [118163] ERROR:  could not find pg_class tuple for index 2662 at character 15
2022-08-01 20:16:23.805 UTC [118163] STATEMENT:  SELECT * FROM pg_publication_tables;
2022-08-01 20:16:23.805 UTC [118163] ERROR:  schema "sch1" does not exist
2022-08-01 20:16:23.805 UTC [118163] STATEMENT:  DROP TABLE sch1.test_multirange_gist;
2022-08-01 20:16:23.805 UTC [118163] ERROR:  schema "sch1" does not exist at character 14
2022-08-01 20:16:23.805 UTC [118163] STATEMENT:  CREATE TABLE sch1.reservations (room_id int) PARTITION BY RANGE(room_id);
2022-08-01 20:16:23.805 UTC [118163] ERROR:  schema "sch1" does not exist at character 14
2022-08-01 20:16:23.805 UTC [118163] STATEMENT:  CREATE TABLE sch1.booked_during PARTITION OF sch1.test_multirange_gist FOR VALUES FROM (10) to (20);
2022-08-01 20:16:23.805 UTC [118163] ERROR:  could not find pg_class tuple for index 2662 at character 15
2022-08-01 20:16:23.805 UTC [118163] STATEMENT:  SELECT * FROM pg_publication_tables;
2022-08-01 20:16:23.806 UTC [118163] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 20:16:23.806 UTC [118163] STATEMENT:  RESET SESSION AUTHORIZATION;
2022-08-01 20:16:23.806 UTC [118163] WARNING:  there is no transaction in progress
2022-08-01 20:16:23.806 UTC [118163] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 20:16:23.806 UTC [118163] STATEMENT:  DISCARD ALL;
2022-08-01 20:16:23.806 UTC [118163] ERROR:  could not find pg_class tuple for index 2662 at character 24
2022-08-01 20:16:23.806 UTC [118163] STATEMENT:  SELECT n.nspname 
	FROM pg_catalog.pg_namespace n 
	WHERE n.nspname !~ '^pg_' AND n.nspname <> 'information_schema';
2022-08-01 20:16:23.806 UTC [118163] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 20:16:23.806 UTC [118163] STATEMENT:  CREATE SCHEMA public; SET search_path TO public;
2022-08-01 20:16:23.810 UTC [118163] ERROR:  could not find pg_class tuple for index 2662 at character 26
2022-08-01 20:16:23.810 UTC [118163] STATEMENT:  select proname, oid from pg_catalog.pg_proc where proname in ('lo_open', 'lo_close', 'lo_creat', 'lo_create', 'lo_unlink', 'lo_lseek', 'lo_lseek64', 'lo_tell', 'lo_tell64', 'lo_truncate', 'lo_truncate64', 'loread', 'lowrite') and pronamespace = (select oid from pg_catalog.pg_namespace where nspname = 'pg_catalog')
	;
2022-08-01 20:16:23.810 UTC [118163] ERROR:  could not find pg_class tuple for index 2662 at character 25
2022-08-01 20:16:23.810 UTC [118163] STATEMENT:  SELECT lo_from_bytea(0, lo_get(32715)) AS newloid_2
	;
2022-08-01 20:16:23.810 UTC [118163] ERROR:  could not find pg_class tuple for index 2662 at character 12
2022-08-01 20:16:23.810 UTC [118163] STATEMENT:  SELECT md5(lo_get(32715)) = md5(lo_get(32722));
2022-08-01 20:16:23.811 UTC [118163] ERROR:  could not find pg_class tuple for index 2662 at character 8
2022-08-01 20:16:23.811 UTC [118163] STATEMENT:  SELECT lo_get(32715, 0, 20);
2022-08-01 20:16:23.811 UTC [118163] WARNING:  there is no transaction in progress
2022-08-01 20:16:23.811 UTC [118163] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 20:16:23.811 UTC [118163] STATEMENT:  DROP ROLE regress_lo_user;
2022-08-01 20:16:23.811 UTC [118163] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 20:16:23.811 UTC [118163] STATEMENT:  RESET SESSION AUTHORIZATION;
2022-08-01 20:16:23.811 UTC [118163] WARNING:  there is no transaction in progress
2022-08-01 20:16:23.811 UTC [118163] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 20:16:23.811 UTC [118163] STATEMENT:  DISCARD ALL;
2022-08-01 20:16:23.811 UTC [118163] ERROR:  could not find pg_class tuple for index 2662 at character 24
2022-08-01 20:16:23.811 UTC [118163] STATEMENT:  SELECT n.nspname 
	FROM pg_catalog.pg_namespace n 
	WHERE n.nspname !~ '^pg_' AND n.nspname <> 'information_schema';
2022-08-01 20:16:23.811 UTC [118163] ERROR:  could not find pg_class tuple for index 2662
2022-08-01 20:16:23.811 UTC [118163] STATEMENT:  CREATE SCHEMA public; SET search_path TO public;
2022-08-01 20:16:25.801 UTC [124234] PANIC:  could not open critical system index 2662
2022-08-01 20:16:25.803 UTC [117850] LOG:  server process (PID 124234) was terminated by signal 6: Aborted
2022-08-01 20:16:25.803 UTC [117850] LOG:  terminating any other active server processes
2022-08-01 20:16:25.880 UTC [117850] LOG:  all server processes terminated; reinitializing
2022-08-01 20:16:25.897 UTC [124235] LOG:  database system was interrupted; last known up at 2022-08-01 20:15:48 UTC
2022-08-01 20:16:25.910 UTC [124235] LOG:  recovered replication state of node 2 to 0/AABBCCDD
2022-08-01 20:16:25.910 UTC [124235] LOG:  database system was not properly shut down; automatic recovery in progress
2022-08-01 20:16:25.911 UTC [124235] LOG:  redo starts at 0/E2E71D0
2022-08-01 20:16:25.977 UTC [124235] LOG:  invalid record length at 0/E4ADC00: wanted 24, got 0
2022-08-01 20:16:25.977 UTC [124235] LOG:  redo done at 0/E4ADBD8 system usage: CPU: user: 0.05 s, system: 0.00 s, elapsed: 0.06 s
2022-08-01 20:16:25.992 UTC [117850] LOG:  database system is ready to accept connections
2022-08-01 20:16:26.106 UTC [124249] WARNING:  there is no transaction in progress
