	  ALTER COLUMN q2 SET NOT NULL,
	  ALTER COLUMN q2 ADD GENERATED ALWAYS AS IDENTITY,
	  ALTER COLUMN q2 SET DATA TYPE bigint;
2022-08-02 00:03:25.269 UTC [29371] ERROR:  could not find pg_class tuple for index 2662 at character 77
2022-08-02 00:03:25.269 UTC [29371] STATEMENT:  SELECT bank_account_pkey.oid,
	  n.nspname,
	  bank_account_pkey.relname
	FROM pg_catalog.pg_class bank_account_pkey
	     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = bank_account_pkey.relnamespace
	WHERE bank_account_pkey.relname OPERATOR(pg_catalog.~) '^(bank_account_pkey)$' COLLATE pg_catalog.default
	  AND pg_catalog.pg_table_is_visible(bank_account_pkey.oid)
	ORDER BY 2, 3;
2022-08-02 00:03:25.269 UTC [29371] ERROR:  could not find pg_class tuple for index 2662 at character 55
2022-08-02 00:03:25.269 UTC [29371] STATEMENT:  SELECT d4_primary1_pkey.oid::pg_catalog.regclass
	FROM pg_catalog.pg_class d4_primary1_pkey, pg_catalog.pg_inherits d4_primary1_pkey
	WHERE d4_primary1_pkey.oid = d4_primary1_pkey.inhparent AND d4_primary1_pkey.inhrelid = '26384'
	  AND d4_primary1_pkey.relkind != 'p' AND d4_primary1_pkey.relkind != 'd4_primary1_pkey'
	ORDER BY inhseqno;
2022-08-02 00:03:25.269 UTC [29371] ERROR:  could not find pg_class tuple for index 2662 at character 275
2022-08-02 00:03:25.269 UTC [29371] STATEMENT:  SELECT pg_catalog.format_type(seqtypid, NULL) AS "Type",
	       seqstart AS "Start",
	       seqmin AS "Minimum",
	       seqmax AS "Maximum",
	       seqincrement AS "Increment",
	       CASE WHEN seqcycle THEN 'yes' ELSE 'no' END AS "Cycles?",
	       seqcache AS "Cache"
	FROM pg_catalog.pg_sequence
	WHERE seqrelid = '26401';
2022-08-02 00:03:25.269 UTC [29371] ERROR:  could not find pg_class tuple for index 2662 at character 8
2022-08-02 00:03:25.269 UTC [29371] STATEMENT:  select percent_rank(3) within group (order by x)
	from (values (1),(1),(2),(2),(3),(3),(4),(5)) v(x);
2022-08-02 00:03:25.269 UTC [29371] ERROR:  could not find pg_class tuple for index 2662 at character 14
2022-08-02 00:03:25.269 UTC [29371] STATEMENT:  CREATE TABLE d4_primary2_pkey (pid date NOT NULL, d4_fk text, d4_pid bigint) PARTITION BY RANGE (pid);
2022-08-02 00:03:25.269 UTC [29371] ERROR:  could not find pg_class tuple for index 2662 at character 14
2022-08-02 00:03:25.269 UTC [29371] STATEMENT:  CREATE TABLE itest_child PARTITION OF d4_primary2_pkey (
	    q2 WITH OPTIONS GENERATED ALWAYS AS IDENTITY
	) FOR VALUES FROM ('2016-07-01') TO ('2016-08-01');
2022-08-02 00:03:25.270 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.270 UTC [29371] STATEMENT:  DROP TABLE t;
2022-08-02 00:03:25.270 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.270 UTC [29371] STATEMENT:  SET parallel_tuple_cost = 0;
2022-08-02 00:03:25.270 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.270 UTC [29371] STATEMENT:  SET parallel_leader_participation = off;
2022-08-02 00:03:25.270 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.270 UTC [29371] STATEMENT:  set enable_sort to default;
2022-08-02 00:03:25.270 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.270 UTC [29371] STATEMENT:  set enable_hashagg = true;
2022-08-02 00:03:25.270 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.270 UTC [29371] STATEMENT:  set enable_sort = false;
2022-08-02 00:03:25.270 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.270 UTC [29371] STATEMENT:  RESET SESSION AUTHORIZATION;
2022-08-02 00:03:25.270 UTC [29371] WARNING:  there is no transaction in progress
2022-08-02 00:03:25.271 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.271 UTC [29371] STATEMENT:  DISCARD ALL;
2022-08-02 00:03:25.271 UTC [29371] ERROR:  could not find pg_class tuple for index 2662 at character 24
2022-08-02 00:03:25.271 UTC [29371] STATEMENT:  SELECT n.nspname 
	FROM pg_catalog.pg_namespace n 
	WHERE n.nspname !~ '^pg_' AND n.nspname <> 'information_schema';
2022-08-02 00:03:25.271 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.271 UTC [29371] STATEMENT:  CREATE SCHEMA public; SET search_path TO public;
2022-08-02 00:03:25.272 UTC [29371] ERROR:  could not find pg_class tuple for index 2662 at character 17
2022-08-02 00:03:25.272 UTC [29371] STATEMENT:  
	
	
	CREATE TABLE t (bank_account int);
2022-08-02 00:03:25.272 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.272 UTC [29371] STATEMENT:  
	
	
	CREATE PROCEDURE test_proc6(a int, INOUT b int, INOUT c int)
	LANGUAGE plpythonu
	AS $$
	return (b * a, c * a)
	$$;
2022-08-02 00:03:25.272 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.272 UTC [29371] STATEMENT:  
	
	DO $$
	DECLARE _a int; _b int;
	BEGIN
	  _a := 10; _b := 30;
	  CALL test_proc9(_a, _b);
	  RAISE NOTICE '_a: %, _b: %', _a, _b;
	END
	$$;
2022-08-02 00:03:25.272 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.272 UTC [29371] STATEMENT:  
	DROP PROCEDURE test_proc2;
2022-08-02 00:03:25.272 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.272 UTC [29371] STATEMENT:  RESET SESSION AUTHORIZATION;
2022-08-02 00:03:25.272 UTC [29371] WARNING:  there is no transaction in progress
2022-08-02 00:03:25.272 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.272 UTC [29371] STATEMENT:  DISCARD ALL;
2022-08-02 00:03:25.272 UTC [29371] ERROR:  could not find pg_class tuple for index 2662 at character 24
2022-08-02 00:03:25.272 UTC [29371] STATEMENT:  SELECT n.nspname 
	FROM pg_catalog.pg_namespace n 
	WHERE n.nspname !~ '^pg_' AND n.nspname <> 'information_schema';
2022-08-02 00:03:25.273 UTC [29371] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:03:25.273 UTC [29371] STATEMENT:  CREATE SCHEMA public; SET search_path TO public;
2022-08-02 00:03:26.845 UTC [40090] PANIC:  could not open critical system index 2662
2022-08-02 00:03:26.847 UTC [28883] LOG:  server process (PID 40090) was terminated by signal 6: Aborted
2022-08-02 00:03:26.847 UTC [28883] LOG:  terminating any other active server processes
2022-08-02 00:03:26.886 UTC [28883] LOG:  all server processes terminated; reinitializing
2022-08-02 00:03:26.902 UTC [40093] LOG:  database system was interrupted; last known up at 2022-08-02 00:02:33 UTC
2022-08-02 00:03:26.925 UTC [40093] LOG:  database system was not properly shut down; automatic recovery in progress
2022-08-02 00:03:26.926 UTC [40093] LOG:  redo starts at 0/3C617D70
2022-08-02 00:03:27.561 UTC [40093] LOG:  invalid record length at 0/3EAF9C30: wanted 24, got 0
2022-08-02 00:03:27.561 UTC [40093] LOG:  redo done at 0/3EAF9BF8 system usage: CPU: user: 0.47 s, system: 0.15 s, elapsed: 0.63 s
2022-08-02 00:03:27.597 UTC [28883] LOG:  database system is ready to accept connections
2022-08-02 00:03:27.825 UTC [40144] WARNING:  there is no transaction in progress
2022-08-02 00:03:27.830 UTC [40144] ERROR:  directory "/root/postgres/src/test/recovery/tmp_check/tmp_test_cUlt" does not exist
