2022-08-02 00:56:21.581 UTC [24539] STATEMENT:  
	INSERT INTO test1 SELECT i from generate_series(1, 10000) i;
2022-08-02 00:56:21.581 UTC [24539] LOG:  request for BRIN range summarization for index "b" page 450 was not recorded
2022-08-02 00:56:21.581 UTC [24539] STATEMENT:  
	INSERT INTO test1 SELECT i from generate_series(1, 10000) i;
2022-08-02 00:56:21.581 UTC [24539] LOG:  request for BRIN range summarization for index "b" page 451 was not recorded
2022-08-02 00:56:21.581 UTC [24539] STATEMENT:  
	INSERT INTO test1 SELECT i from generate_series(1, 10000) i;
2022-08-02 00:56:21.581 UTC [24539] LOG:  request for BRIN range summarization for index "b" page 452 was not recorded
2022-08-02 00:56:21.581 UTC [24539] STATEMENT:  
	INSERT INTO test1 SELECT i from generate_series(1, 10000) i;
2022-08-02 00:56:21.581 UTC [24539] LOG:  request for BRIN range summarization for index "b" page 453 was not recorded
2022-08-02 00:56:21.581 UTC [24539] STATEMENT:  
	INSERT INTO test1 SELECT i from generate_series(1, 10000) i;
2022-08-02 00:56:21.594 UTC [24539] ERROR:  conflicting or redundant options at character 36
2022-08-02 00:56:21.594 UTC [24539] STATEMENT:  COPY test1 from stdin (freeze off, freeze on);
2022-08-02 00:56:21.666 UTC [24539] ERROR:  conflicting or redundant options at character 41
2022-08-02 00:56:21.666 UTC [24539] STATEMENT:  COPY test1 from stdin (force_quote (a), force_quote *);
2022-08-02 00:56:21.675 UTC [24539] ERROR:  role "regress_priv_user7" does not exist
2022-08-02 00:56:21.675 UTC [24539] STATEMENT:  GRANT pg_write_all_data TO regress_priv_user7;
2022-08-02 00:56:21.706 UTC [24539] WARNING:  there is no transaction in progress
2022-08-02 00:56:21.733 UTC [24539] WARNING:  there is no transaction in progress
2022-08-02 00:56:21.741 UTC [24539] ERROR:  role "regress_priv_user8" does not exist
2022-08-02 00:56:21.741 UTC [24539] STATEMENT:  REVOKE ADMIN OPTION FOR pg_read_all_settings FROM regress_priv_user8;
2022-08-02 00:56:21.749 UTC [24539] WARNING:  there is no transaction in progress
2022-08-02 00:56:21.756 UTC [24539] ERROR:  relation "base_fn_out" does not exist
2022-08-02 00:56:21.756 UTC [24539] STATEMENT:  COPY base_fn_out (test_tab_pkey, test_tab) FROM STDIN WITH (FORMAT csv, FORCE_NULL(e));
2022-08-02 00:56:21.764 UTC [24539] ERROR:  role "regress_priv_group1" does not exist
2022-08-02 00:56:21.764 UTC [24539] STATEMENT:  ALTER GROUP regress_priv_group1 ADD USER regress_priv_user4;
2022-08-02 00:56:21.771 UTC [24539] ERROR:  role "regress_priv_group2" does not exist
2022-08-02 00:56:21.771 UTC [24539] STATEMENT:  ALTER GROUP regress_priv_group2 DROP USER regress_priv_user2;
2022-08-02 00:56:21.810 UTC [24539] ERROR:  role "regress_priv_user1" does not exist
2022-08-02 00:56:21.810 UTC [24539] STATEMENT:  GRANT regress_priv_role TO regress_priv_user1 WITH ADMIN OPTION GRANTED BY CURRENT_ROLE;
2022-08-02 00:56:21.841 UTC [24539] ERROR:  function fn_x_before() does not exist
2022-08-02 00:56:21.841 UTC [24539] STATEMENT:  DROP FUNCTION fn_x_before();
2022-08-02 00:56:21.874 UTC [24539] ERROR:  table "description" does not exist
2022-08-02 00:56:21.874 UTC [24539] STATEMENT:  DROP TABLE description;
2022-08-02 00:56:21.904 UTC [24539] ERROR:  role "regress_priv_user1" does not exist
2022-08-02 00:56:21.904 UTC [24539] STATEMENT:  REVOKE ADMIN OPTION FOR regress_priv_role FROM regress_priv_user1 GRANTED BY foo;
2022-08-02 00:56:21.935 UTC [24539] ERROR:  role "regress_priv_user1" does not exist
2022-08-02 00:56:21.935 UTC [24539] STATEMENT:  REVOKE ADMIN OPTION FOR regress_priv_role FROM regress_priv_user1 GRANTED BY CURRENT_USER;
2022-08-02 00:56:22.033 UTC [24539] ERROR:  role "regress_priv_user2" does not exist
2022-08-02 00:56:22.033 UTC [24539] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user2;
2022-08-02 00:56:22.064 UTC [24539] WARNING:  there is no transaction in progress
2022-08-02 00:56:22.096 UTC [24539] ERROR:  could not find pg_class tuple for index 2662 at character 15
2022-08-02 00:56:22.096 UTC [24539] STATEMENT:  SELECT * FROM information_schema.tables WHERE table_schema NOT IN ('pg_catalog', 'information_schema');
2022-08-02 00:56:22.096 UTC [24539] ERROR:  could not find pg_class tuple for index 2662 at character 64
2022-08-02 00:56:22.096 UTC [24539] STATEMENT:  SELECT      n.nspname as schema, t.typname as type FROM        pg_type t LEFT JOIN   pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE       (t.typrelid = 0 OR (SELECT c.relkind = 'c' FROM pg_catalog.pg_class c WHERE c.oid = t.typrelid)) AND     NOT EXISTS(SELECT 1 FROM pg_catalog.pg_type el WHERE el.oid = t.typelem AND el.typarray = t.oid) AND     n.nspname NOT IN ('pg_catalog', 'information_schema');
2022-08-02 00:56:22.096 UTC [24539] ERROR:  could not find pg_class tuple for index 2662 at character 89
2022-08-02 00:56:22.096 UTC [24539] STATEMENT:  SELECT routines.routine_name, parameters.data_type, parameters.ordinal_position 
	  FROM information_schema.routines 
	  LEFT JOIN information_schema.parameters ON routines.specific_name=parameters.specific_name 
	  WHERE routines.specific_schema='public' 
	  ORDER BY routines.routine_name, parameters.ordinal_position;
2022-08-02 00:56:22.097 UTC [24539] ERROR:  could not find pg_class tuple for index 2662 at character 123
2022-08-02 00:56:22.097 UTC [24539] STATEMENT:  SELECT event_object_table      ,trigger_name       ,event_manipulation       ,action_statement       ,action_timing FROM  information_schema.triggers ORDER BY event_object_table      ,event_manipulation;
2022-08-02 00:56:22.097 UTC [24539] ERROR:  could not find pg_class tuple for index 2662 at character 15
2022-08-02 00:56:22.097 UTC [24539] STATEMENT:  select * from pg_indexes where tablename not like 'pg%';
2022-08-02 00:56:22.097 UTC [24539] ERROR:  could not find pg_class tuple for index 2662 at character 22
2022-08-02 00:56:22.097 UTC [24539] STATEMENT:  select rulename
	from pg_rewrite r  
	  join pg_class c on r.ev_class = c.oid 
	  left join pg_namespace n on n.oid = c.relnamespace 
	  left join pg_description d on r.oid = d.objoid
	where n.nspname = 'public';
	
2022-08-02 00:56:22.097 UTC [24539] ERROR:  could not find pg_class tuple for index 2662 at character 22
2022-08-02 00:56:22.097 UTC [24539] STATEMENT:  select viewname from pg_catalog.pg_views
	where schemaname NOT IN ('pg_catalog', 'information_schema')
	order by schemaname, viewname;
2022-08-02 00:56:22.097 UTC [24539] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 00:56:22.097 UTC [24539] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user4;
2022-08-02 00:56:22.097 UTC [24539] ERROR:  could not find pg_class tuple for index 2662 at character 15
2022-08-02 00:56:22.097 UTC [24539] STATEMENT:  SELECT * FROM information_schema.tables WHERE table_schema NOT IN ('pg_catalog', 'information_schema');
2022-08-02 00:56:22.097 UTC [24539] ERROR:  could not find pg_class tuple for index 2662 at character 64
2022-08-02 00:56:22.097 UTC [24539] STATEMENT:  SELECT      n.nspname as schema, t.typname as type FROM        pg_type t LEFT JOIN   pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE       (t.typrelid = 0 OR (SELECT c.relkind = 'c' FROM pg_catalog.pg_class c WHERE c.oid = t.typrelid)) AND     NOT EXISTS(SELECT 1 FROM pg_catalog.pg_type el WHERE el.oid = t.typelem AND el.typarray = t.oid) AND     n.nspname NOT IN ('pg_catalog', 'information_schema');
2022-08-02 00:56:22.097 UTC [24539] ERROR:  could not find pg_class tuple for index 2662 at character 89
2022-08-02 00:56:22.097 UTC [24539] STATEMENT:  SELECT routines.routine_name, parameters.data_type, parameters.ordinal_position 
	  FROM information_schema.routines 
	  LEFT JOIN information_schema.parameters ON routines.specific_name=parameters.specific_name 
	  WHERE routines.specific_schema='public' 
	  ORDER BY routines.routine_name, parameters.ordinal_position;
2022-08-02 00:56:22.097 UTC [24539] ERROR:  could not find pg_class tuple for index 2662 at character 123
2022-08-02 00:56:22.097 UTC [24539] STATEMENT:  SELECT event_object_table      ,trigger_name       ,event_manipulation       ,action_statement       ,action_timing FROM  information_schema.triggers ORDER BY event_object_table      ,event_manipulation;
2022-08-02 00:56:22.097 UTC [24539] ERROR:  could not find pg_class tuple for index 2662 at character 15
2022-08-02 00:56:22.097 UTC [24539] STATEMENT:  select * from pg_indexes where tablename not like 'pg%';
2022-08-02 00:56:22.097 UTC [24539] ERROR:  could not find pg_class tuple for index 2662 at character 22
2022-08-02 00:56:22.097 UTC [24539] STATEMENT:  select rulename
	from pg_rewrite r  
	  join pg_class c on r.ev_class = c.oid 
	  left join pg_namespace n on n.oid = c.relnamespace 
	  left join pg_description d on r.oid = d.objoid
	where n.nspname = 'public';
	
2022-08-02 00:56:22.097 UTC [24539] ERROR:  could not find pg_class tuple for index 2662 at character 22
2022-08-02 00:56:22.097 UTC [24539] STATEMENT:  select viewname from pg_catalog.pg_views
	where schemaname NOT IN ('pg_catalog', 'information_schema')
	order by schemaname, viewname;
2022-08-02 00:56:22.101 UTC [24539] FATAL:  could not find pg_class tuple for index 2662
2022-08-02 00:56:22.617 UTC [24629] PANIC:  could not open critical system index 2662
2022-08-02 00:56:22.618 UTC [24266] LOG:  server process (PID 24629) was terminated by signal 6: Aborted
2022-08-02 00:56:22.618 UTC [24266] LOG:  terminating any other active server processes
2022-08-02 00:56:22.619 UTC [24633] FATAL:  the database system is in recovery mode
2022-08-02 00:56:22.619 UTC [24266] LOG:  all server processes terminated; reinitializing
2022-08-02 00:56:22.628 UTC [24638] LOG:  database system was interrupted; last known up at 2022-08-02 00:56:21 UTC
2022-08-02 00:56:22.638 UTC [24638] LOG:  database system was not properly shut down; automatic recovery in progress
2022-08-02 00:56:22.638 UTC [24638] LOG:  redo starts at 0/167ADF8
2022-08-02 00:56:22.652 UTC [24638] LOG:  invalid record length at 0/1855108: wanted 24, got 0
2022-08-02 00:56:22.652 UTC [24638] LOG:  redo done at 0/18504B0 system usage: CPU: user: 0.01 s, system: 0.00 s, elapsed: 0.01 s
2022-08-02 00:56:22.655 UTC [24266] LOG:  database system is ready to accept connections
2022-08-02 00:56:22.851 UTC [24266] LOG:  received smart shutdown request
