| | | info: thd memory_used: 53536  size: -16416
| | <my_free
| <net_end
| >innobase_rollback_trx
| | trans: aborting transaction
| <innobase_rollback_trx
| mutex: mutex (0x52b5200) locking
| mutex: mutex (0x52b5200) locked
| mutex: mutex (0x52b5200) unlocking
| mutex: mutex (0x6120000012a0) locking
| mutex: mutex (0x6120000012a0) locked
| mutex: mutex (0x6120000012a0) unlocking
| mutex: LOCK_thd_data (0x62b00015ffe8) locking
| mutex: LOCK_thd_data (0x62b00015ffe8) locked
| mutex: LOCK_thd_data (0x62b00015ffe8) unlocking
| >plugin_unlock
| | mutex: LOCK_plugin (0x6022f20) locking
| | mutex: LOCK_plugin (0x6022f20) locked
| | >intern_plugin_unlock
| | | >my_free
| | | | my: ptr: 0x60e000186ae8
| | | | info: global thd memory_used: -552  size: -32
| | | <my_free
| | | lock: thd: 0x62b00015e288  plugin: "InnoDB" UNLOCK ref_count: 39
| | <intern_plugin_unlock
| | mutex: LOCK_plugin (0x6022f20) unlocking
| <plugin_unlock
| >plugin_thdvar_cleanup
| | >my_free
| | | my: ptr: 0x611000242f48
| | | info: thd memory_used: 37120  size: -120
| | <my_free
| | mutex: LOCK_plugin (0x6022f20) locking
| | mutex: LOCK_plugin (0x6022f20) locked
| | >intern_plugin_unlock
| | | >my_free
| | | | my: ptr: 0x60e00019cd48
| | | | info: global thd memory_used: -584  size: -32
| | | <my_free
| | | lock: thd: 0x62b00015e288  plugin: "InnoDB" UNLOCK ref_count: 38
| | <intern_plugin_unlock
| | >intern_plugin_unlock
| | <intern_plugin_unlock
| | >intern_plugin_unlock
| | <intern_plugin_unlock
| | >my_free
| | | my: ptr: 0x0
| | <my_free
| | >my_free
| | | my: ptr: 0x0
| | <my_free
| | >my_free
| | | my: ptr: 0x612000212348
| | | info: global thd memory_used: -616  size: -152
| | <my_free
| | mutex: LOCK_plugin (0x6022f20) unlocking
| <plugin_thdvar_cleanup
| info: freeing security context
| >my_free
| | my: ptr: 0x60e00015bb28
| | info: global thd memory_used: -768  size: -32
| <my_free
| >my_free
| | my: ptr: 0x60e000189e88
| | info: global thd memory_used: -800  size: -40
| <my_free
| >my_hash_reset
| | enter: hash:0x62b0001601c8
| <my_hash_reset
| >my_hash_reset
| | enter: hash:0x62b000160148
| <my_hash_reset
<unlink_thd
>Thread_cache::park
2022-07-30  3:03:06 5 [ERROR] Got error 194 when reading table './lfclihky/seq1'
2022-07-30  3:03:06 5 [ERROR] Got error 194 when reading table './rxsqribw/seq1'
2022-07-30  3:03:07 5 [ERROR] Got error 194 when reading table './trjiyrru/t1'
2022-07-30  3:03:07 5 [ERROR] Got error 194 when reading table './kxnruxai/seq1'
2022-07-30  3:03:07 5 [ERROR] Got error 194 when reading table './qvqsvhxz/seq1'
2022-07-30  3:03:07 5 [ERROR] Got error 194 when reading table './qvqsvhxz/seq1'
2022-07-30  3:03:07 5 [ERROR] Got error 194 when reading table './qvqsvhxz/seq1'
2022-07-30  3:03:07 5 [ERROR] Got error 194 when reading table './qvqsvhxz/seq1'
2022-07-30  3:03:07 5 [ERROR] Got error 194 when reading table './qvqsvhxz/seq1'
2022-07-30  3:03:07 5 [ERROR] Got error 194 when reading table './gocgcaqv/seq1'
2022-07-30  3:03:07 5 [ERROR] Got error 194 when reading table './atiujdwj/seq1'
2022-07-30  3:03:07 5 [ERROR] Got error 194 when reading table './yemiqale/seq1'
2022-07-30  3:03:07 5 [ERROR] Got error 194 when reading table './ggrqfito/seq1'
2022-07-30  3:03:07 5 [ERROR] Got error 194 when reading table './otjbogbp/seq1'
2022-07-30  3:03:07 5 [ERROR] Got error 194 when reading table './bmllphuq/seq1'
2022-07-30  3:03:08 5 [ERROR] Got error 194 when reading table './liybkkis/seq1'
2022-07-30  3:03:08 5 [ERROR] Got error 194 when reading table './szizhdox/seq1'
2022-07-30  3:03:08 5 [ERROR] Got error 194 when reading table './zxynfccg/seq1'
2022-07-30  3:03:08 5 [ERROR] Got error 194 when reading table './qotfvpxj/seq1'
2022-07-30  3:03:08 5 [Note] InnoDB: Sync to disk of `kpoqusmq`.`seq1` started.
2022-07-30  3:03:08 5 [Note] InnoDB: Stopping purge
2022-07-30  3:03:08 5 [Note] InnoDB: Writing table metadata to './kpoqusmq/seq1.cfg'
2022-07-30  3:03:08 5 [Note] InnoDB: Table `kpoqusmq`.`seq1` flushed to disk
2022-07-30  3:03:08 5 [Note] InnoDB: Deleting the meta-data file './kpoqusmq/seq1.cfg'
2022-07-30  3:03:08 5 [Note] InnoDB: Resuming purge
2022-07-30  3:03:08 5 [ERROR] Got error 194 when reading table './xlxiggnq/seq1'
